# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwo <- function(x) {
    .Call(`_CreateDataframeFromMap_timesTwo`, x)
}

#' Create a Dataframe Using Rcpp
#' 
#' This is the example from Seamless R and C++ from page 55.
create_dataframe <- function() {
    .Call(`_CreateDataframeFromMap_create_dataframe`)
}

rcpp_hello_world <- function() {
    .Call(`_CreateDataframeFromMap_rcpp_hello_world`)
}

